version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docs:/app/docs                 # 当前目录docs映射
    command: /bin/sh -c "npm run build"  # 启动时构建并运行
  